services:
    frontend_backend:
        image: node:20-alpine
        container_name: vue_frontend_backend
        working_dir: /app
        ports:
            - '3000:3000'
        volumes:
            - ./front_back:/app
        command: sh -c "npm install && npm run dev"
        environment:
            - NODE_ENV=development
            - DB_HOST=${DB_HOST}
            - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING=true
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
            - MAIL_USER=${MAIL_USER}
            - MAIL_PASS=${MAIL_PASS}
        depends_on:
            db:
                condition: service_healthy

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        volumes:
            - mysql_data:/var/lib/mysql
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - '3306:3306'
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            interval: 5s
            timeout: 5s
            retries: 5

    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports:
            - '8080:8080'
        depends_on:
            - db

volumes:
    mysql_data:
